/**
 * Copyright (C) 2026 by Outlast.
 */
import type { IdentityConfig } from "@fonoster/identity";
import {
  OUTLAST_IDENTITY_ACCESS_TOKEN_EXPIRES_IN,
  OUTLAST_IDENTITY_AUDIENCE,
  OUTLAST_IDENTITY_CLOAK_ENCRYPTION_KEY,
  OUTLAST_IDENTITY_CONTACT_VERIFICATION_REQUIRED,
  OUTLAST_IDENTITY_DATABASE_URL,
  OUTLAST_IDENTITY_GITHUB_CLIENT_ID,
  OUTLAST_IDENTITY_GITHUB_CLIENT_SECRET,
  OUTLAST_IDENTITY_ID_TOKEN_EXPIRES_IN,
  OUTLAST_IDENTITY_ISSUER,
  OUTLAST_IDENTITY_PRIVATE_KEY,
  OUTLAST_IDENTITY_PUBLIC_KEY,
  OUTLAST_IDENTITY_REFRESH_TOKEN_EXPIRES_IN,
  OUTLAST_IDENTITY_SMTP_HOST,
  OUTLAST_IDENTITY_SMTP_PASS,
  OUTLAST_IDENTITY_SMTP_PORT,
  OUTLAST_IDENTITY_SMTP_SECURE,
  OUTLAST_IDENTITY_SMTP_SENDER,
  OUTLAST_IDENTITY_SMTP_USER,
  OUTLAST_IDENTITY_TWILIO_ACCOUNT_SID,
  OUTLAST_IDENTITY_TWILIO_AUTH_TOKEN,
  OUTLAST_IDENTITY_TWILIO_PHONE_NUMBER,
  OUTLAST_IDENTITY_TWO_FACTOR_AUTH_REQUIRED,
  OUTLAST_IDENTITY_WORKSPACE_INVITE_EXPIRATION,
  OUTLAST_IDENTITY_WORKSPACE_INVITE_FAIL_URL,
  OUTLAST_IDENTITY_WORKSPACE_INVITE_URL
} from "./envs.js";

export const identityConfig: IdentityConfig = {
  dbUrl: OUTLAST_IDENTITY_DATABASE_URL,
  issuer: OUTLAST_IDENTITY_ISSUER,
  audience: OUTLAST_IDENTITY_AUDIENCE,
  privateKey: OUTLAST_IDENTITY_PRIVATE_KEY,
  publicKey: OUTLAST_IDENTITY_PUBLIC_KEY,
  encryptionKey: OUTLAST_IDENTITY_CLOAK_ENCRYPTION_KEY,
  accessTokenExpiresIn: OUTLAST_IDENTITY_ACCESS_TOKEN_EXPIRES_IN,
  refreshTokenExpiresIn: OUTLAST_IDENTITY_REFRESH_TOKEN_EXPIRES_IN,
  idTokenExpiresIn: OUTLAST_IDENTITY_ID_TOKEN_EXPIRES_IN,
  workspaceInviteExpiration: OUTLAST_IDENTITY_WORKSPACE_INVITE_EXPIRATION,
  workspaceInviteUrl: OUTLAST_IDENTITY_WORKSPACE_INVITE_URL,
  workspaceInviteFailUrl: OUTLAST_IDENTITY_WORKSPACE_INVITE_FAIL_URL,
  contactVerificationRequired: OUTLAST_IDENTITY_CONTACT_VERIFICATION_REQUIRED,
  twoFactorAuthenticationRequired: OUTLAST_IDENTITY_TWO_FACTOR_AUTH_REQUIRED,
  smtpConfig: {
    sender: OUTLAST_IDENTITY_SMTP_SENDER,
    host: OUTLAST_IDENTITY_SMTP_HOST,
    port: OUTLAST_IDENTITY_SMTP_PORT,
    secure: OUTLAST_IDENTITY_SMTP_SECURE,
    auth: {
      user: OUTLAST_IDENTITY_SMTP_USER,
      pass: OUTLAST_IDENTITY_SMTP_PASS
    }
  },
  twilioSmsConfig: OUTLAST_IDENTITY_TWILIO_ACCOUNT_SID
    ? {
        accountSid: OUTLAST_IDENTITY_TWILIO_ACCOUNT_SID,
        authToken: OUTLAST_IDENTITY_TWILIO_AUTH_TOKEN,
        sender: OUTLAST_IDENTITY_TWILIO_PHONE_NUMBER
      }
    : undefined,
  githubOauth2Config: OUTLAST_IDENTITY_GITHUB_CLIENT_ID
    ? {
        clientId: OUTLAST_IDENTITY_GITHUB_CLIENT_ID,
        clientSecret: OUTLAST_IDENTITY_GITHUB_CLIENT_SECRET
      }
    : undefined
};
