/**
 * Copyright (C) 2026 by Outlast. MIT License.
 *
 * @outlast/identity - Identity gateway module
 */
export {
  identityRouter,
  type IdentityRouter,
  createIdentityContext,
  type IdentityContext
} from "./trpc/index.js";
export { createIdentityPrismaClient } from "./db.js";
export { identityConfig } from "./identityConfig.js";
export { setupIdentityDatabase } from "./setupDatabase.js";
export {
  OUTLAST_IDENTITY_DATABASE_URL,
  OUTLAST_IDENTITY_CLOAK_ENCRYPTION_KEY,
  OUTLAST_IDENTITY_PRIVATE_KEY,
  OUTLAST_IDENTITY_PUBLIC_KEY,
  OUTLAST_IDENTITY_ISSUER,
  OUTLAST_IDENTITY_AUDIENCE,
  OUTLAST_IDENTITY_ACCESS_TOKEN_EXPIRES_IN,
  OUTLAST_IDENTITY_REFRESH_TOKEN_EXPIRES_IN,
  OUTLAST_IDENTITY_ID_TOKEN_EXPIRES_IN,
  OUTLAST_IDENTITY_WORKSPACE_INVITE_EXPIRATION,
  OUTLAST_IDENTITY_WORKSPACE_INVITE_URL,
  OUTLAST_IDENTITY_WORKSPACE_INVITE_FAIL_URL,
  OUTLAST_IDENTITY_CONTACT_VERIFICATION_REQUIRED,
  OUTLAST_IDENTITY_TWO_FACTOR_AUTH_REQUIRED,
  OUTLAST_IDENTITY_SMTP_SENDER,
  OUTLAST_IDENTITY_SMTP_HOST,
  OUTLAST_IDENTITY_SMTP_PORT,
  OUTLAST_IDENTITY_SMTP_SECURE,
  OUTLAST_IDENTITY_SMTP_USER,
  OUTLAST_IDENTITY_SMTP_PASS,
  OUTLAST_IDENTITY_TWILIO_ACCOUNT_SID,
  OUTLAST_IDENTITY_TWILIO_AUTH_TOKEN,
  OUTLAST_IDENTITY_TWILIO_PHONE_NUMBER,
  OUTLAST_IDENTITY_GITHUB_CLIENT_ID,
  OUTLAST_IDENTITY_GITHUB_CLIENT_SECRET
} from "./envs.js";
